language: node_js  
node_js: "node"  
services: mongodb  
cache:  
  directories:
    - "node_modules"
  yarn: true
install:
    - npm install -g codecov
script:
    - ./node_modules/nyc/bin/nyc.js ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
    - codecov